guestOS = {
    "asianux3-64" : "Asianux Server 3 (64-bit)",
    "asianux3" : "Asianux Server 3 (32-bit)",
    "asianux4-64" : "Asianux Server 4 (64-bit)",
    "asianux4" : "Asianux Server 4 (32-bit)",
    "asianux5-64" : "Asianux Server 5 (64-bit)",
    "asianux7-64" : "Asianux Server 7 (64-bit)",
    "centos6-64" : "CentOS 6 (64-bit)",
    "centos64" : "CentOS 4/5 (64-bit)",
    "centos6" : "CentOS 6 (32-bit)",
    "centos7-64" : "CentOS 7 (64-bit)",
    "centos7" : "CentOS 7 (32-bit)",
    "centos" : "CentOS 4/5 (32-bit)",
    "coreos64" : "CoreOS Linux (64-bit)",
    "darwin10-64" : "Mac OS 10.6 (64-bit)",
    "darwin10" : "Mac OS 10.6 (32-bit)",
    "darwin11-64" : "Mac OS 10.7 (64-bit)",
    "darwin11" : "Mac OS 10.7 (32-bit)",
    "darwin12-64" : "Mac OS 10.8 (64-bit)",
    "darwin13-64" : "Mac OS 10.9 (64-bit)",
    "darwin14-64" : "Mac OS 10.10 (64-bit)",
    "darwin15-64" : "Mac OS 10.11 (64-bit)",
    "darwin16-64" : "Mac OS 10.12 (64-bit)",
    "darwin17-64" : "Mac OS 10.13 (64-bit)",
    "darwin18-64" : "Mac OS 10.14 (64-bit)",
    "darwin64" : "Mac OS 10.5 (64-bit)",
    "darwin" : "Mac OS 10.5 (32-bit)",
    "debian10-64" : "Debian GNU/Linux 10 (64-bit)",
    "debian10" : "Debian GNU/Linux 10 (32-bit)",
    "debian4-64" : "Debian GNU/Linux 4 (64-bit)",
    "debian4" : "Debian GNU/Linux 4 (32-bit)",
    "debian5-64" : "Debian GNU/Linux 5 (64-bit)",
    "debian5" : "Debian GNU/Linux 5 (32-bit)",
    "debian6-64" : "Debian GNU/Linux 6 (64-bit)",
    "debian6" : "Debian GNU/Linux 6 (32-bit)",
    "debian7-64" : "Debian GNU/Linux 7 (64-bit)",
    "debian7" : "Debian GNU/Linux 7 (32-bit)",
    "debian8-64" : "Debian GNU/Linux 8 (64-bit)",
    "debian8" : "Debian GNU/Linux 8 (32-bit)",
    "debian9-64" : "Debian GNU/Linux 9 (64-bit)",
    "debian9" : "Debian GNU/Linux 9 (32-bit)",
    "dos" : "Microsoft MS-DOS.",
    "eComStation2" : "eComStation 2.0",
    "eComStation" : "eComStation 1.x",
    "fedora64" : "Fedora Linux (64-bit)",
    "fedora" : "Fedora Linux (32-bit)",
    "freebsd64" : "FreeBSD (64-bit)",
    "freebsd" : "FreeBSD (32-bit)",
    "genericLinux" : "Other Linux",
    "mandrake" : "Mandrake Linux",
    "mandriva64" : "Mandriva Linux (64-bit)",
    "mandriva" : "Mandriva Linux (32-bit)",
    "netware4" : "Novell NetWare 4",
    "netware5" : "Novell NetWare 5.1",
    "netware6" : "Novell NetWare 6.x",
    "nld9" : "Novell Linux Desktop 9",
    "oes" : "Open Enterprise Server",
    "openServer5" : "SCO OpenServer 5",
    "openServer6" : "SCO OpenServer 6",
    "opensuse64" : "OpenSUSE Linux (64-bit)",
    "opensuse" : "OpenSUSE Linux (32-bit)",
    "oracleLinux6-64" : "Oracle 6 (64-bit)",
    "oracleLinux64" : "Oracle Linux 4/5 (64-bit)",
    "oracleLinux6" : "Oracle 6 (32-bit)",
    "oracleLinux7-64" : "Oracle 7 (64-bit)",
    "oracleLinux7" : "Oracle 7 (32-bit)",
    "oracleLinux" : "Oracle Linux 4/5",
    "os2" : "IBM OS/2",
    "other24xLinux64" : "Linux 2.4x Kernel (64-bit)",
    "other24xLinux" : "Linux 2.4x Kernel (32-bit)",
    "other26xLinux64" : "Linux 2.6x Kernel (64-bit)",
    "other26xLinux" : "Linux 2.6x Kernel (32-bit)",
    "other3xLinux64" : "Linux 3.x Kernel (64-bit)",
    "other3xLinux" : "Linux 3.x Kernel (32-bit)",
    "other" : "Other Operating System (32-bit)",
    "other64" : "Other Operating System (64-bit)",
    "otherLinux64" : "Linux (64-bit)",
    "otherLinux" : "Linux 2.2x Kernel (32-bit)",
    "redhat" : "Red Hat Linux 2.1",
    "rhel2" : "Red Hat Enterprise Linux 2",
    "rhel3-64" : "Red Hat Enterprise Linux 3 (64-bit)",
    "rhel3" : "Red Hat Enterprise Linux 3 (32-bit)",
    "rhel4-64" : "Red Hat Enterprise Linux 4 (64-bit)",
    "rhel4" : "Red Hat Enterprise Linux 4 (32-bit)",
    "rhel5-64" : "Red Hat Enterprise Linux 5 (64-bit)",
    "rhel5" : "Red Hat Enterprise Linux 5 (32-bit)",
    "rhel6-64" : "Red Hat Enterprise Linux 6 (64-bit)",
    "rhel6" : "Red Hat Enterprise Linux 6 (32-bit)",
    "rhel7-64" : "Red Hat Enterprise Linux 7 (64-bit)",
    "rhel7" : "Red Hat Enterprise Linux 7 (32-bit)",
    "sjds" : "Sun Java Desktop System",
    "sles10-64" : "Suse Linux Enterprise Server 10 (64-bit)",
    "sles10" : "Suse Linux Enterprise Server 10 (32-bit)",
    "sles11-64" : "Suse Linux Enterprise Server 11 (64-bit)",
    "sles11" : "Suse Linux Enterprise Server 11 (32-bit)",
    "sles12-64" : "Suse Linux Enterprise Server 12 (64-bit)",
    "sles12" : "Suse Linux Enterprise Server 12 (32-bit)",
    "sles64" : "Suse Linux Enterprise Server 9 (64-bit)",
    "sles" : "Suse Linux Enterprise Server 9 (32-bit)",
    "solaris10-64" : "Solaris 10 (64-bit)",
    "solaris10" : "Solaris 10 (32-bit)",
    "solaris11-64" : "Solaris 11 (64-bit)",
    "solaris6" : "Solaris 6",
    "solaris7" : "Solaris 7",
    "solaris8" : "Solaris 8",
    "solaris9" : "Solaris 9",
    "suse64" : "Suse Linux (64-bit)",
    "suse" : "Suse Linux (32-bit)",
    "turboLinux64" : "Turbolinux (64-bit)",
    "turboLinux" : "Turbolinux (32-bit)",
    "ubuntu64" : "Ubuntu Linux (64-bit)",
    "ubuntu" : "Ubuntu Linux (32-bit)",
    "unixWare7" : "SCO UnixWare 7",
    "vmkernel5" : "VMware ESX 5",
    "vmkernel65" : "VMware ESX 6.5",
    "vmkernel6" : "VMware ESX 6",
    "vmkernel" : "VMware ESX 4",
    "vmwarePhoton64" : "VMware Photon (64-bit)",
    "win2000AdvServ" : "Microsoft Windows 2000 Advanced Server",
    "win2000Pro" : "Microsoft Windows 2000 Professional",
    "win2000Serv" : "Microsoft Windows 2000 Server",
    "win31" : "Microsoft Windows 3.1",
    "win95" : "Microsoft Windows 95",
    "win98" : "Microsoft Windows 98",
    "windows7-64" : "Microsoft Windows 7 (64-bit)",
    "windows7" : "Microsoft Windows 7 (32-bit)",
    "windows7Server64" : "Microsoft Windows Server 2008 R2 (64-bit)",
    "windows8-64" : "Microsoft Windows 8 (64-bit)",
    "windows8" : "Microsoft Windows 8 (32-bit)",
    "windows8Server64" : "Microsoft Windows Server 2012 (64 bit)",
    "windows9-64" : "Microsoft Windows 10 (64-bit)",
    "windows9" : "Microsoft Windows 10 (32-bit)",
    "windows9Server64" : "Microsoft Windows Server 2016 (64-bit)",
    "windowsHyperV" : "Microsoft Windows Hyper-V",
    "winLonghorn64" : "Microsoft Windows Longhorn (64-bit)",
    "winLonghorn" : "Microsoft Windows Longhorn (32-bit)",
    "winMe" : "Microsoft Windows Millenium Edition",
    "winNetBusiness" : "Microsoft Windows Small Business Server 2003",
    "winNetDatacenter64" : "Microsoft Windows Server 2003, Datacenter Edition (64-bit)",
    "winNetDatacenter" : "Microsoft Windows Server 2003, Datacenter Edition (32-bit)",
    "winNetEnterprise64" : "Microsoft Windows Server 2003, Enterprise Edition (64-bit)",
    "winNetEnterprise" : "Microsoft Windows Server 2003, Enterprise Edition (32-bit)",
    "winNetStandard64" : "Microsoft Windows Server 2003, Standard Edition (64-bit)",
    "winNetStandard" : "Microsoft Windows Server 2003, Standard Edition (32-bit)",
    "winNetWeb" : "Microsoft Windows Server 2003, Web Edition",
    "winNT" : "Microsoft Windows NT 4",
    "winVista64" : "Microsoft Windows Vista (64-bit)",
    "winVista" : "Microsoft Windows Vista",
    "winXPHome" : "Microsoft Windows XP Home Edition",
    "winXPPro64" : "Microsoft Windows XP Professional Edition (64-bit)",
    "winXPPro" : "Microsoft Windows XP Professional (32-bit)"
}